### ISSUE TITLE
Something is missing here

### ISSUE THREAD

**Issue by d0k3** [ps1dr3x/greenpass-generator#3]
Compare with the results from this page:
https://dgc.a-sit.at/ehn/

QR Codes scanned from there actually pass everything but the signature check, while QR codes generated by greenpass-generator don't. I have no clue what's missing here, though. Already tried the (3 byte?) header.

**Comment by Steuerboykott** [comment]
Anyone interested in hacking the EU Green Pass tyranny can get from me what I found on Telegram. I found private keys on Telegram, but I don't know exactly how to implement them to a working program that creates certificates. There was one project on Github that could create certificates in the correct format, but they were not recognized to be valid.
Send me your message by email and include your Github user name, so I can check if you are contributing something useful. If you are working on a web tool so everyone (!) can create their own and valid certificate from home, you have my sympathy.
Programmers: I will send you what I have and you then will create some certificates from names and birthdates given by me. If I have proof, then let's release to the public. My concern is interest-free if it's for the use of all.
My political standpoint is (all in German) here...

- Marcel Barz: Die Pandemie in den Rohdaten, https://www.youtube.com/watch?v=nEPiOEkkWzg
- Tom Lausen beim Exomagazin, https://www.youtube.com/watch?v=oqUtg6oPJBU
- Tom Lausen bei Punkt.PRERADOVIC, https://www.youtube.com/watch?v=0sBM7MVG8Lo
- Sebastian Götz: Die Zerstörung des Corona Hypes, https://www.youtube.com/watch?v=Juugv0T7inc
- Sebastian Götz: Haben wir Corona unterschätzt?, https://www.youtube.com/watch?v=rDBn1f8CSZI
- Paul Schreyer: Pandemie-Planspiele – Vorbereitung einer neuen Ära, https://www.youtube.com/watch?v=SSnJhHOU_28

**Comment by BenKing87** [comment]
@Steuerboykott: firstly i was quite happy to see someone interested in hacking the EU-Pass. From my perspective it is quite usefull to try to hack something that whole europe is going to use. CCC showed us how risky IT can be on a national level (for example the elections.) Then i saw your links and oh - boy.

Maybe stop watching youtube as basis for a policical standpoint. 

https://www.volksverpetzer.de/corona-faktencheck/pandemie-in-den-rohdaten/?gclid=EAIaIQobChMI7-WyorSL9AIVjed3Ch3JHAl-EAAYASAAEgJsQPD_BwE

**Comment by d0k3** [comment]
Oh well.

Stop hijacking my issue. This is not kindergarten. In general, politics and ideological positions have no place here.

Closing this myself due to off-topic. I answered the question I asked myself already anyways, if @ps1dr3x is interested in the answer, they may just contact me.

**Comment by Steuerboykott** [comment]
Hi there!

I don't see what you want to tell me by sending me this link to volksverpetzer.de. They do not prove anything, neither that Marcel Bartz ist wrong nor the oppisite. It's only babbling. However, you can stell me where Marcel Bartz was wrong or what he misrepresented. I am not interested in your ideologies, only facts count. So don't send me left-wing articles from lockdown lovers. Thanks.


9. Nov. 2021, 14:47 von ***@***.***:

**Comment by Steuerboykott** [comment]
"politics and ideological positions have no place here."
Complete facepalm, hmm? So if you have these good standards, then why do you send me a link to an article by one of the most radical left there is? Do you even know where they get funds from?

**Comment by Steuerboykott** [comment]
Please write by email.

**Comment by d0k3** [comment]
Just to make this clear. I didn't post any link to any ideological stuff here.

And @BenKing87 - there's no reason for you to give me a thumbs up here. Your posting is not any more welcome here than his is, and your sources are for sure not any "better" than his sources are.

**Comment by BenKing87** [comment]
@d0k3 apologies for missusing the issue for political stuff.

**Comment by Steuerboykott** [comment]
How often do you want to repeat the phrase, that ideological stuff should be kept out, but then you use ideological arguments yourself?! All my links do not contain any ideological things. Those videos are by honest truth seekers. If you reference to those fake fact checkers, maybe you are part of an ideological program, hmm?
